<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="ApplicationBuilderHelpers" Version="4.1.86" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain.SourceGenerators\Domain.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Infrastructure.Sqlite" />
		<InternalsVisibleTo Include="Infrastructure.Python" />
		<InternalsVisibleTo Include="Infrastructure.FileSystem" />
		<InternalsVisibleTo Include="Presentation.Api" />
	</ItemGroup>

</Project>
