<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<BaseCommandType>Presentation.Commands.BaseCommand</BaseCommandType>
		<OutputType>Exe</OutputType>
		<EnableNsDepCop>false</EnableNsDepCop>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyTitle>GenTurbo CLI</AssemblyTitle>
		<AssemblyName>genturbo</AssemblyName>
		<Description>CLI application for GenTurbo distributed media generation platform.</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Infrastructure.Sqlite\Infrastructure.Sqlite.csproj" />
		<ProjectReference Include="..\Infrastructure.Python\Infrastructure.Python.csproj" />
		<ProjectReference Include="..\Infrastructure.FileSystem\Infrastructure.FileSystem.csproj" />
		<ProjectReference Include="..\Presentation\Presentation.csproj" />
	</ItemGroup>

</Project>
