<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<InternalsVisibleTo Include="genturbo-server" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

</Project>
