<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsTrimmable>false</IsTrimmable>
		<EnableTrimAnalyzer>false</EnableTrimAnalyzer>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CSnakes.Runtime" Version="1.2.1" />
	</ItemGroup>

	<ItemGroup>
		<None Include="PythonModules\**\*.py">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<LinkBase>PythonModules\</LinkBase>
		</None>
		<None Include="PythonModules\**\requirements.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<LinkBase>PythonModules\</LinkBase>
		</None>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="genturbo-server" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

</Project>
