<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsTrimmable>false</IsTrimmable>
		<EnableTrimAnalyzer>false</EnableTrimAnalyzer>
	</PropertyGroup>

	<ItemGroup>
		<None Include="PythonModules\models\z-image-turbo\**\*.py">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<LinkBase>PythonModules\models\z-image-turbo\</LinkBase>
		</None>
		<None Include="PythonModules\models\z-image-turbo\**\requirements.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<LinkBase>PythonModules\models\z-image-turbo\</LinkBase>
		</None>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="genturbo-server" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Infrastructure.Python\Infrastructure.Python.csproj" />
	</ItemGroup>

</Project>
